--Categorias
INSERT INTO CATEGORY(ID, NAME) VALUES(1, 'Alimentos');
INSERT INTO CATEGORY(ID, NAME) VALUES(2, 'Eletrodomésticos');
INSERT INTO CATEGORY(ID, NAME) VALUES(3, 'Móveis');

--Produtos

--Alimentos
INSERT INTO PRODUCT(ID, NAME, ID_CATEGORY) VALUES(1, 'Arroz', 1);
INSERT INTO PRODUCT(ID, NAME, ID_CATEGORY) VALUES(2, 'Feijão', 1);

--Eletrodomésticos
INSERT INTO PRODUCT(ID, NAME, ID_CATEGORY) VALUES(3, 'Aspirador de pó', 2);
INSERT INTO PRODUCT(ID, NAME, ID_CATEGORY) VALUES(4, 'Batedeira', 2);
INSERT INTO PRODUCT(ID, NAME, ID_CATEGORY) VALUES(5, 'Liquidificador', 2);

--Móveis
INSERT INTO PRODUCT(ID, NAME, ID_CATEGORY) VALUES(6, 'Sofá', 3);
INSERT INTO PRODUCT(ID, NAME, ID_CATEGORY) VALUES(7, 'Mesa', 3);
INSERT INTO PRODUCT(ID, NAME, ID_CATEGORY) VALUES(8, 'Estante', 3);