CREATE TABLE CATEGORY(
  ID BIGINT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCT(
	ID BIGINT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	ID_CATEGORY BIGINT NOT NULL
);

ALTER TABLE PRODUCT ADD FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID);